// content.js — 学习地图的全部知识内容（数据，不含交互逻辑）
// 更新知识请阅读 docs/CONTENT_UPDATE_GUIDE.md，并遵守 AGENTS.md 的内容编辑标准。

const modules = [
 {id:'workflow',n:'01',p:'P0',title:'Workflow & Process Redesign',q:'AI 到底接管哪些工作？',desc:'把传统流程重构成人 + Agent 的 AI-native workflow，而不仅仅是在旧流程上加一个聊天机器人。',concepts:['Agentic Workflow','Deterministic Workflow','Human-in-the-loop','Trigger','Checkpoint','Evaluator–Optimizer','Parallel / Sequential','Workflow Redesign'],tools:[['Taskade Genesis','从业务描述生成 App + Agent + Automation'],['CrewAI Flows','固定流程与 Agent Crew 混合'],['LangGraph','用 State / Node / Edge 编排流程'],['Microsoft Agent Framework','Agent + Workflow + Checkpoint + HITL']],learn:'重点学“固定流程 vs Agent 自主判断”的边界；学会把一个真实业务流程拆成：确定性规则、Agent 判断、人工审批、异常升级。',deep:{
   intro:'很多组织的第一反应是“在原来的流程上加一个 AI 助手”——报销流程不变，只是多一个能问答的机器人。这几乎不会带来真正的效率提升，因为瓶颈往往不在“回答问题”，而在流程本身的结构。AI-native 的做法是反过来问：如果一部分判断和执行可以交给 Agent，这条流程本来应该长什么样？于是流程被拆成三种角色分工——确定性规则（该写死的写死）、Agent 判断（需要理解上下文、灵活处理的交给 Agent）、人类把关（高风险、不可逆、需要担责的留给人）。这一章是整张地图的起点：先想清楚“工作怎么重新分配”，后面的 Context（Agent 要知道什么）、Agent 架构（谁来执行）、治理（谁来负责）才有意义。',
   keyConcepts:[
    ['确定性流程 vs Agentic 流程','确定性流程每一步都写死、结果可预测，适合规则清晰、不容出错的环节（如金额校验、审批路由）；Agentic 流程让 Agent 根据上下文临场决定下一步，适合难以穷举规则的环节（如归类模糊工单、起草回复）。真实流程通常是两者混合，关键是想清楚每一步该用哪种。'],
    ['Human-in-the-loop（人在环中）','把高风险、不可逆或需要担责的步骤保留给人审批或纠正，例如大额支付、对外发布、删除数据。它不是“AI 不够好才加人”，而是有意的风险设计：让 Agent 处理量，让人守住关键闸口。'],
    ['Trigger 与 Checkpoint','Trigger 是流程的起点——定时、收到消息、状态变化或人工发起；Checkpoint 是流程中的检查点，用来保存状态、插入人工确认，或在出错时回退恢复。设计流程时先问：什么触发它？哪里需要能停下来检查？'],
    ['Evaluator–Optimizer 模式','一个 Agent 负责产出、另一个负责评估并提改进意见，循环迭代直到达标。适合质量要求高、一次难做对的任务（如文案、代码、方案），是把“Agent 会犯错”变成“Agent 能自我改进”的常用结构。'],
   ],
   links:[
    ['Anthropic · Building Effective Agents','https://www.anthropic.com/engineering/building-effective-agents','入门必读。用最朴素的语言讲清 workflow 与 agent 的区别，以及几种常见编排模式（prompt chaining、routing、parallelization、evaluator-optimizer）。适合先建立整体心智。'],
    ['OpenAI · A Practical Guide to Building Agents (PDF)','https://cdn.openai.com/business-guides-and-resources/a-practical-guide-to-building-agents.pdf','面向落地的实践指南，讲什么任务适合交给 Agent、如何设计护栏与人工介入。偏“怎么做”，适合读完上一篇后看。'],
    ['LangGraph · Workflows 教程','https://langchain-ai.github.io/langgraph/tutorials/workflows/','动手教程。把上面的编排模式用代码跑一遍，能直观理解“确定性 vs Agent 判断”在工程上如何实现。看不懂代码也能读懂结构。'],
    ['CrewAI · Flows 文档','https://docs.crewai.com/concepts/flows','另一种视角：把固定流程（Flow）与角色化 Agent 结合。对照 LangGraph 看，能体会不同框架对“流程编排”的不同理解。'],
   ],
   path:[
    '先读 Anthropic《Building Effective Agents》，建立 workflow vs agent 的整体概念，不用记术语。',
    '再读 OpenAI 实践指南，重点看“什么任务适合 Agent”和“哪里必须留人”。',
    '挑一个你熟悉的真实流程（如请假、报销、工单处理），亲手把它拆成：确定性规则 / Agent 判断 / 人工把关。',
    '有余力再翻 LangGraph 或 CrewAI 教程，看这些拆分在工程上怎么落地——理解结构即可，不必会写。',
   ],
   tools:[
    {name:'LangGraph',object:'一等对象是「流程图」——用 State（状态）、Node（节点）、Edge（边）把 Agent 工作流画成一张可控的图。',links:[['官网','https://www.langchain.com/langgraph'],['文档','https://langchain-ai.github.io/langgraph/']],learn:'最适合理解“确定性 vs Agent 判断”如何在工程上落地。先跑官方 quickstart，重点体会 State 怎么在节点间流动、条件边怎么决定下一步。'},
    {name:'CrewAI',object:'一等对象是「角色化的 Agent Crew + Flow」——给每个 Agent 分配角色（如研究员、审稿人），再用 Flow 把固定流程和 Agent 判断结合。',links:[['官网','https://www.crewai.com/'],['Flows 文档','https://docs.crewai.com/concepts/flows']],learn:'和 LangGraph 对照着看，体会“按角色组队”与“按图编排”两种不同思路。适合喜欢从“团队分工”角度理解多步流程的人。'},
    {name:'Microsoft Agent Framework',object:'一等对象是「企业级 Agent + Workflow」——把 Agent、工作流、Checkpoint、人工介入打包成面向企业的框架。',links:[['官方文档','https://learn.microsoft.com/en-us/agent-framework/']],learn:'关注它怎么把 Checkpoint（检查点）和 Human-in-the-loop（人工介入）作为一等能力内建——这正是本模块“哪里留人、哪里能回退”的工程答案。'},
    {name:'Taskade Genesis',object:'一等对象是「生成出来的业务系统」——用一句业务描述生成 App + Agent + Automation，是“流程重构”最直观的样本。',links:[['官网','https://www.taskade.com/'],['帮助中心','https://help.taskade.com/']],learn:'不用写代码就能体验“描述业务 → 得到一个含 Agent 和自动化的系统”。适合先建立感性认识：AI-native 流程长什么样。'},
   ]
  }},
 {id:'context',n:'02',p:'P0',title:'Context & Memory',q:'AI 怎么知道该知道的东西？',desc:'从“知识库”升级为 Context Infrastructure：让 Agent 在正确时间拿到正确的组织知识、历史和状态。',concepts:['Context Engineering','Working Memory','Long-term Memory','Episodic Memory','Semantic Memory','RAG','State','Context Compression','Continual Learning'],tools:[['Letta','Stateful / Lifelong Agent 与长期状态'],['Mem0','面向 Agent 的 Memory Layer'],['LangGraph Memory','把状态与记忆放进 Agent workflow'],['企业知识库 / RAG','组织知识进入 Agent 的基础方式']],learn:'重点理解 Memory ≠ 聊天记录；以及“某个 Agent 在某个任务、某个时刻应该知道什么”这个 Context Engineering 问题。'},
 {id:'agent',n:'03',p:'P0',title:'Agent Architecture',q:'一个 Agent 到底怎么持续完成任务？',desc:'理解 Agent 的运行底盘：模型只是大脑，真正能工作还需要 Harness、工具、状态、沙箱与循环。',concepts:['Agent Loop','Plan–Act–Observe','Tool Use','Harness','Runtime','Sandbox','Skill','Computer Use','Session'],tools:[['DeepSeek Harness (DSH)','理解 Model + Harness 的好教材'],['LangGraph','低层 Agent / State 编排'],['Microsoft Agent Framework','企业 Agent Runtime / Workflow'],['Codex / Claude Code','观察成熟 Coding Agent 的实际工作方式']],learn:'不用钻源码，但必须真正理解 Agent Loop、Harness、Skill、Tool、Sandbox、Session 分别解决什么问题。'},
 {id:'tools',n:'04',p:'P0',title:'Tool & System Connectivity',q:'Agent 怎么连接组织已有系统？',desc:'Agent 真正进入企业，核心不是会聊天，而是能安全读取数据、调用能力、操作已有软件。',concepts:['MCP','Tool Calling','Connector','API','Resource','Authorization','Computer Use','MCP Server'],tools:[['MCP','Agent ↔ Tools / Data 的关键开放协议'],['MCP Server','把企业系统能力暴露给 Agent'],['Connectors','连接 Gmail / Drive / Slack / CRM 等'],['Computer Use','没有 API 时直接操作软件界面']],learn:'MCP 建议升为必修：搞懂 Host、Client、Server、Tool、Resource、Authorization；不要求你会写 Server。'},
 {id:'multi',n:'05',p:'P1',title:'Multi-Agent & Orchestration',q:'什么时候需要多个 Agent？',desc:'核心不是“多个 Agent 聊天”，而是 Delegation、Handoff、共享状态、Supervisor 与并行协作。',concepts:['Subagent','Supervisor','Router','Delegation','Handoff','Parallelization','Shared State','Orchestrator'],tools:[['LangGraph','图式多 Agent 编排'],['CrewAI','按角色建立 Agent Crew'],['Microsoft Agent Framework','多 Agent + Workflow'],['Moxt','在 Workspace 中观察多 Agent 协作']],learn:'最重要的问题不是“怎么做更多 Agent”，而是：什么时候一个 Agent + Skills 已经足够，什么时候拆分才真的提高质量或效率。'},
 {id:'a2a',n:'06',p:'P1',title:'Agent Interoperability',q:'不同 Agent 如何跨系统协作？',desc:'当 Agent 来自不同厂商、不同团队时，需要 Discovery、身份描述、任务委派与状态返回。',concepts:['A2A','Agent Card','Agent Discovery','Cross-agent Delegation','Interop','Remote Agent'],tools:[['A2A Protocol','重点理解 Agent ↔ Agent'],['MCP','与 A2A 对照：Agent ↔ Tools/Data'],['Agent Card','Agent 能力与身份的可发现描述'],['跨厂商 Agent 协作','关注协议而非单一平台']],learn:'先搞懂 MCP 与 A2A 的分工即可。A2A 属于观察中的关键协议，不必现在深入实现细节。'},
 {id:'workspace',n:'07',p:'P0',title:'Human-Agent Workspace',q:'人和 Agent 在哪里共同工作？',desc:'Workspace 不是 UI 外壳，而是共享 Context、文件、任务、状态、历史、权限与干预入口。',concepts:['Agent-native Workspace','Shared Context','Persistent Workspace','AI Teammate','Human-Agent Team','Agent Board','Shared Files'],tools:[['Moxt','典型 Agent-native Workspace'],['Meco','AI Coworker / 产品团队协作'],['Asana AI Teammates','从 Work Management 容纳 Agent'],['Multica','Human + Agent Work Management']],learn:'观察“如果 40% 团队成员是 Agent，Workspace 要怎么设计”：身份、任务、@、Inbox、共享历史、权限、状态、离职/下线。'},
 {id:'app',n:'08',p:'P1',title:'AI-native App / Living Software',q:'软件本身会不会变成 Agent 系统？',desc:'从固定逻辑的软件，走向 Memory + Intelligence + Execution 持续循环的“活软件”。',concepts:['Living Software','Agentic App','Memory → Intelligence → Execution','Generated Business System','Agent-native App'],tools:[['Taskade Genesis','最直观的 Living Software 样本'],['AI App Builder','观察 App + Database + Agent + Automation 的融合'],['Internal Tool Builder','企业内部系统的 Agent 化方向']],learn:'重点理解“在软件里加 AI”与“软件本身就是 Agentic System”的区别。'},
 {id:'gov',n:'09',p:'P0',title:'Governance',q:'Agent 被允许做什么？谁负责？',desc:'Agent 规模化以后必须像员工和软件资产一样被登记、授权、审计、审批和下线。',concepts:['Agent Identity','Permission','Owner','Agent Registry','Policy','Approval','Audit','Lifecycle','Shadow Agent'],tools:[['Microsoft Agent 365','Agent 身份、权限、治理、生命周期'],['Google Agent Registry','统一登记 Agents / Tools / Skills / MCP'],['Enterprise IAM','理解 Agent 如何进入企业身份体系'],['Approval Layer','高风险行为的人类审批机制']],learn:'这是与你职业方向非常匹配的一块。试着设计：Agent 创建、Owner、授权、敏感动作、审计、版本升级、撤权、下线的完整治理规则。'},
 {id:'ops',n:'10',p:'P0',title:'Evaluation & AgentOps',q:'怎么知道 Agent 干得好不好？',desc:'Agent 是概率系统，不能只看最终答案；还要看运行轨迹、工具调用、成本、失败率和人工纠正。',concepts:['Trace','Eval','Observability','Trajectory','Regression','Cost','Completion Rate','Escalation Rate','Human Correction'],tools:[['LangSmith','Trace / Eval / Monitor / Human Feedback'],['Arize Phoenix','LLM / Agent Observability'],['Braintrust','Evaluation、实验与生产质量'],['DSH Session Log','理解 Agent 运行轨迹与可追溯性']],learn:'学会设计 Agent 指标：成功率、人工接管率、错误类型、成本、延迟、越权、重复失败、用户纠正率。'},
 {id:'workforce',n:'11',p:'P1',title:'AI Workforce & Agent Management',q:'Agent 从工具变成“组织资源”后怎么管理？',desc:'Persistent AI Teammate、Agent Fleet、Role-based Agent 和 Control Plane 都在把 Agent 当成可长期运营的数字劳动力。',concepts:['AI Employee','AI Teammate','Agent Fleet','Agent Control Plane','Role-based Agent','Routine','Persistent Agent'],tools:[['Grok Bot','Role-centric / Persistent AI Teammate'],['Asana AI Teammates','Agent 进入真实工作管理系统'],['Multica','Human-Agent 任务与项目管理'],['CrewAI Enterprise','Agent Crew / 企业化管理思路']],learn:'重点区分 Task-centric Agent 和 Role-centric Agent；观察 Agent 是否拥有长期职责、Memory、Routine、Owner、权限和绩效。'},
 {id:'org',n:'12',p:'P0',title:'Organization Design & Transformation',q:'最终人的岗位和组织怎样改变？',desc:'这是最终目标：从部署 Agent 上升到重新设计岗位、决策权、管理跨度、Operating Model 与组织能力。',concepts:['AI-native Organization','Role Redesign','Decision Rights','Human-in-the-loop','Management Span','Operating Model','Organizational Feedback Loop'],tools:[['Microsoft Work Trend Index','观察 Human-Agent Team 与组织趋势'],['OpenAI 企业实践','观察 workflow design / governance / adoption'],['Anthropic 企业 Agent 案例','观察从单步到多阶段 Agent workflow'],['真实企业试点','最终必须回到业务流程与组织实践']],learn:'长期研究，不追求一次学完。你的最终专业能力应是：把 Workflow、Context、Agent、Workspace、Governance 组合成可运行的组织变革方案。'}
];

const products=[
 ['Moxt','Agent-native Workspace','Workspace / Multi-Agent','重点看共享 Context、Agent Board、持久项目空间与人-Agent协作。'],
 ['Meco','AI Coworker Workspace','Workspace / Organization','把 AI PM、AI Tech Lead 等角色当作团队成员。'],
 ['Asana AI Teammates','Human-Agent Work Management','Workspace / Governance','从传统工作管理系统向人+Agent共同工作转型。'],
 ['Multica','Human + Agent Project Management','Workspace / Control Plane','统一管理人、Agent、任务、状态与多种 Coding Agent。'],
 ['Taskade Genesis','AI-native App / Living Software','Workflow / App','用 Memory + Agent + Automation + UI 生成业务系统。'],
 ['DeepSeek Harness (DSH)','Agent Harness / Runtime','Agent Architecture','理解 Model + Harness、插件化、Session、Subagent 与 Workflow。'],
 ['LangGraph','Agent / Workflow Graph','Workflow / Multi-Agent','State、Node、Edge；适合理解可控 Agent workflow。'],
 ['CrewAI','Agent Crew + Flows','Workflow / Multi-Agent','角色化 Agent Crew 与更确定的 Flow 结合。'],
 ['Microsoft Agent Framework','Enterprise Agent Framework','Agent / Workflow','Agent、Workflow、Checkpoint、Human-in-the-loop 等。'],
 ['MCP','Agent ↔ Tools/Data Protocol','Connectivity','Agent 连接企业工具、数据和能力的关键协议。'],
 ['A2A','Agent ↔ Agent Protocol','Interoperability','跨 Agent 的发现、委派、协作与状态沟通。'],
 ['Letta','Stateful / Lifelong Agent','Memory','长期状态、Memory 与持续学习型 Agent。'],
 ['Mem0','Memory Layer','Memory','跨 Session / Agent 的持久化记忆层。'],
 ['LangSmith','Agent Observability / Eval','AgentOps','Trace、评估、监控、人工反馈。'],
 ['Arize Phoenix','LLM / Agent Observability','AgentOps','面向 Agent 的可观测性与分析。'],
 ['Braintrust','AI Evaluation Platform','AgentOps','评测、实验、回归与生产质量。'],
 ['Microsoft Agent 365','Agent Governance','Governance','身份、权限、Owner、风险、生命周期。'],
 ['Google Agent Registry','Agent Registry','Governance','统一登记 Agents、Tools、Skills、MCP 等。'],
 ['Grok Bot','Persistent AI Teammate','AI Workforce','把 Cloud Agent 封装为长期角色、Routine 与持久工作环境。']
];

const conceptDefs = {
 'Agentic Workflow':'流程中部分步骤由 Agent 根据上下文动态决定下一步，而不是完全写死。',
 'Human-in-the-loop':'高风险或不确定步骤由人审批、纠正或接管。',
 'Context Engineering':'设计 Agent 在特定任务时应该看到哪些信息、以什么结构看到。',
 'RAG':'先从知识库检索相关内容，再交给模型生成或判断。',
 'Agent Loop':'Agent 反复经历观察 → 推理/计划 → 行动 → 再观察，直到完成或停止。',
 'Harness':'把模型变成可工作的 Agent 所需的工具、Session、沙箱、Memory、Loop 等运行层。',
 'MCP':'面向 Agent 连接工具和数据的开放协议。',
 'A2A':'面向 Agent 与 Agent 之间发现、委派和协作的协议。',
 'Skill':'可复用的专业能力或工作方法，可被 Agent 在合适任务中调用。',
 'Subagent':'被主 Agent 委派执行某个子任务的独立 Agent。',
 'Handoff':'把任务、责任和必要上下文从一个 Agent 转交给另一个 Agent。',
 'Orchestrator':'协调多个 Agent、工具和工作步骤的总控角色。',
 'Agent-native Workspace':'从一开始就假设人和 Agent 都是成员的工作空间。',
 'Agent Identity':'Agent 在企业中的独立身份，用于权限、审计、Owner 与生命周期管理。',
 'Agent Registry':'集中登记和管理组织内 Agent、工具、技能和端点。',
 'AgentOps':'围绕 Agent 的运行、质量、成本、监控、评测、版本和生命周期的运营体系。',
 'Trace':'记录一次 Agent 运行中模型、工具、子 Agent、输入输出等完整轨迹。',
 'Eval':'用系统化指标或测试集评价 Agent 的质量，而不是凭感觉。',
 'Persistent Agent':'长期存在、保留上下文/环境，并持续承担职责的 Agent。',
 'AI Teammate':'以团队成员/岗位而非一次任务执行器来设计的 Agent。',
 'Living Software':'数据、Agent 与自动化持续循环运行的软件形态，而非固定逻辑程序。',
 'Organizational Feedback Loop':'Agent 执行结果进入评估与知识系统，再反过来改进流程、Context 和 Agent。',
 'Deterministic Workflow':'每一步都被规则写死、结果可预测的流程，不依赖 Agent 临场判断。',
 'Trigger':'触发流程或 Agent 开始工作的事件，如定时、消息、状态变化或人工发起。',
 'Checkpoint':'流程中的检查点，用于保存状态、人工确认或在出错时回退与恢复。',
 'Evaluator–Optimizer':'一个 Agent 产出结果、另一个负责评估并给出改进意见的迭代模式。',
 'Parallel / Sequential':'任务是并行同时做还是按顺序逐步做，是流程编排的基本选择。',
 'Workflow Redesign':'围绕人 + Agent 的新能力重新设计流程，而不是在旧流程上加 AI。',
 'Working Memory':'Agent 当前任务里正在使用的短期上下文，类似人脑的临时记忆。',
 'Long-term Memory':'跨任务、跨会话长期保存并可被反复调用的知识与经验。',
 'Episodic Memory':'关于“发生过什么事”的记忆，如某次任务的具体经过与结果。',
 'Semantic Memory':'关于“事实与概念”的记忆，如业务规则、定义、结构化知识。',
 'State':'Agent 或流程在某一时刻的完整状态数据，用于继续执行或恢复。',
 'Context Compression':'在上下文窗口有限时，把长历史压缩成要点以保留关键信息。',
 'Continual Learning':'Agent 从新经验中持续更新知识或行为，而不是训练完就固定。',
 'Plan–Act–Observe':'Agent 循环的核心步骤：先计划、再行动、再观察结果并调整。',
 'Tool Use':'Agent 调用外部工具（搜索、代码、API 等）来完成靠模型本身做不到的事。',
 'Runtime':'真正让 Agent 跑起来的运行环境，管理会话、状态、工具与执行循环。',
 'Sandbox':'隔离的安全执行环境，让 Agent 运行代码或操作时不影响真实系统。',
 'Computer Use':'在没有 API 时，Agent 直接像人一样操作图形界面（点击、输入）。',
 'Session':'一次完整的 Agent 工作过程，包含其上下文、状态与执行轨迹。',
 'Tool Calling':'模型按结构化格式请求调用某个工具并接收返回结果的机制。',
 'Connector':'把 Agent 接入具体外部系统（如 Gmail、Drive、CRM）的连接件。',
 'API':'系统对外暴露能力的标准接口，是 Agent 读写数据、调用功能的基础。',
 'Resource':'MCP 中 Server 暴露给 Agent 读取的数据或内容（文件、记录等）。',
 'Authorization':'授权机制：决定某个 Agent 被允许访问哪些数据、执行哪些操作。',
 'MCP Server':'按 MCP 协议把某个系统的工具和数据暴露给 Agent 的服务端。',
 'Supervisor':'负责统筹、分派并监督多个下级 Agent 的主控 Agent。',
 'Router':'根据任务类型把请求分发到合适 Agent 或流程分支的调度角色。',
 'Delegation':'把某个子任务及必要上下文交给另一个 Agent 去执行。',
 'Parallelization':'把可拆分的工作同时交给多个 Agent 并行处理以提高效率。',
 'Shared State':'多个 Agent 共同读写的一份状态，用于协作时保持信息一致。',
 'Agent Card':'描述一个 Agent 身份、能力和调用方式的标准化清单，便于被发现。',
 'Agent Discovery':'在系统中找到可用 Agent 及其能力的机制，是跨 Agent 协作前提。',
 'Cross-agent Delegation':'把任务从一个厂商/系统的 Agent 委派给另一个的能力。',
 'Interop':'不同来源的 Agent 能相互理解、协作的互操作性。',
 'Remote Agent':'运行在其他系统或厂商处、通过协议被远程调用的 Agent。',
 'Shared Context':'人与 Agent 共同可见、共同使用的上下文（文件、任务、历史等）。',
 'Persistent Workspace':'长期存在、保留项目状态与历史的工作空间，而非一次性会话。',
 'Human-Agent Team':'把人和 Agent 当作同一个团队的成员来组织与协作。',
 'Agent Board':'展示各 Agent 当前任务、状态与进度的看板式界面。',
 'Shared Files':'人与 Agent 都能读写的共享文件区，是协作的物质载体。',
 'Agentic App':'以 Agent 为核心运行逻辑的应用，而非固定流程的传统软件。',
 'Memory → Intelligence → Execution':'活软件的循环：记忆积累 → 智能判断 → 执行动作，再回流。',
 'Generated Business System':'由 AI 根据业务描述生成的、含数据与自动化的完整系统。',
 'Agent-native App':'从设计之初就假设 Agent 是主要使用者/执行者的应用形态。',
 'Permission':'规定某个 Agent 能访问什么、能做什么的权限设置。',
 'Owner':'对某个 Agent 负责的人或团队，承担其行为与后果。',
 'Policy':'约束 Agent 行为的规则集合，如可用工具、禁止动作、审批要求。',
 'Approval':'高风险动作在执行前必须由人类批准的控制环节。',
 'Audit':'完整记录 Agent 做过什么、以便事后追溯与问责。',
 'Lifecycle':'Agent 从创建、上线、升级到停用/下线的完整生命周期管理。',
 'Shadow Agent':'未登记、无 Owner、脱离治理的“影子 Agent”，是重要风险点。',
 'Observability':'能看清 Agent 内部运行（调用、轨迹、成本、错误）的可观测能力。',
 'Trajectory':'一次 Agent 运行经过的完整步骤序列，用于分析质量与失败原因。',
 'Regression':'新版本导致原本正常的能力变差，需用回归测试及早发现。',
 'Cost':'一次 Agent 运行消耗的资源与费用（Token、调用、时间等）。',
 'Completion Rate':'Agent 独立成功完成任务的比例，是核心质量指标之一。',
 'Escalation Rate':'Agent 无法处理而升级给人工的比例，反映其自主能力边界。',
 'Human Correction':'人工对 Agent 输出的纠正，既是质量信号也是改进来源。',
 'AI Employee':'被当作长期数字员工、拥有职责与权限来管理的 Agent。',
 'Agent Fleet':'一个组织里成规模运行、需统一管理的一批 Agent。',
 'Agent Control Plane':'统一管理、调度、监控与治理大量 Agent 的控制平面。',
 'Role-based Agent':'围绕某个岗位/角色设计、承担长期职责的 Agent，而非一次性任务。',
 'Routine':'Agent 反复执行的固定职责或例行工作流程。',
 'AI-native Organization':'从流程、岗位到治理都以“人 + Agent 协作”为前提设计的组织。',
 'Role Redesign':'当 Agent 承担部分工作后，对人的岗位职责重新划分与设计。',
 'Decision Rights':'明确哪些决策由人拍板、哪些可交给 Agent 的决策权分配。',
 'Management Span':'一个管理者能有效带领的对象数量，在人 + Agent 下会改变。',
 'Operating Model':'组织如何组织资源、流程与人 + Agent 来持续交付价值的方式。'

};

// 每个模块的最后更新日期（YYYY-MM-DD）。更新某模块内容后，把对应日期改为当天。
const moduleUpdated={workflow:'2026-09-16',context:'2026-09-16',agent:'2026-09-16',tools:'2026-09-16',multi:'2026-09-16',a2a:'2026-09-16',workspace:'2026-09-16',app:'2026-09-16',gov:'2026-09-16',ops:'2026-09-16',workforce:'2026-09-16',org:'2026-09-16'};
